package com.pidev.swing;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;

import javax.imageio.ImageIO;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.pidev.persistence.Job;
import com.pidev.services.JobServicesRemote;
import com.pidev.test.Home;
import com.sun.mail.handlers.image_jpeg;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

public class JobList extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form JobList
     */
	
	JobServicesRemote proxy = null;
	Context ctx = null;
    
	
	
		public JobList() {
			initComponents();
			a();
		}
    
    
    private void a(){
 	   
 	   String[] columnNames = {"Id",
               "Title" ,
               "Cost",
                "State",
                
                "Fund of user"
                };
 	   try{
 		   ctx = new InitialContext();
 		   proxy = (JobServicesRemote) ctx.lookup("ejb:/Pidev-EJB/JobServices!com.pidev.services.JobServicesRemote");
 		   
 	   }catch(NamingException ex){
 		   ex.printStackTrace();
 		   
 	   }

 	   List<Job> allofThem = proxy.findAllJobs();

 	   Object[][] data=new Object[allofThem.size()][5];
 	   
 	   
 	   for (int i=0;i<allofThem.size();i++)
 	   {
 		   data[i][0]=allofThem.get(i).getId();
 		   data[i][1]=allofThem.get(i).getTitle();
 		   data[i][2]=allofThem.get(i).getCost();
 		   data[i][3]=allofThem.get(i).getState();
 		   data[i][4]=allofThem.get(i).getUserid();
 	   }

 	   jTable1.setModel(new DefaultTableModel(data,columnNames){/**
 	    * 
 	    */
 		   private static final long serialVersionUID = 1L;
 		   
 		   public boolean isCellEditable(int row, int col) {
 			   return false;
 		   }});
 	   
 	   
    }
 
	
	
	

	
 
 	
    
    
     
     
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        
        
        
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        //setBackground(imageUpdate(img, NORMAL, MAXIMIZED_BOTH, MAXIMIZED_BOTH, MAXIMIZED_BOTH, MAXIMIZED_BOTH));
        
        
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reject/Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Job Proposals Manager");
                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                layout.setHorizontalGroup(
                	layout.createParallelGroup(Alignment.LEADING)
                		.addGroup(layout.createSequentialGroup()
                			.addContainerGap()
                			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 553, GroupLayout.PREFERRED_SIZE)
                			.addPreferredGap(ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                				.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                				.addComponent(jButton2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                				.addComponent(jButton3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                			.addGap(38))
                		.addGroup(layout.createSequentialGroup()
                			.addGap(112)
                			.addComponent(jLabel1)
                			.addContainerGap(267, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                	layout.createParallelGroup(Alignment.TRAILING)
                		.addGroup(layout.createSequentialGroup()
                			.addContainerGap()
                			.addComponent(jLabel1)
                			.addPreferredGap(ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                				.addGroup(layout.createSequentialGroup()
                					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
                					.addGap(67)
                					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                					.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
                				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 285, GroupLayout.PREFERRED_SIZE))
                			.addGap(82))
                );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	int a = jTable1.getSelectedRow();
        int aa=(int)jTable1.getValueAt(a,0);
        int ab=(int)jTable1.getValueAt(a,4);
        String ac=jTable1.getValueAt(a,3).toString();
        String message = "Insufficient fund";
        String message1 = "Already verified";
        Job job = new Job();
        job=proxy.findJobById(aa);
        
        
        if(ac.equalsIgnoreCase("On hold")){
        if(job.getCost()<=ab  ){
        	
        	job.setState("Verified");
            proxy.update(job);
            a();
        	
        }
        else {
        	
        	JOptionPane.showMessageDialog(new JFrame(), message,
					"Alerte", JOptionPane.INFORMATION_MESSAGE);
					}
        }else{  
        	JOptionPane.showMessageDialog(new JFrame(), message1,
				"Alerte", JOptionPane.INFORMATION_MESSAGE); 
        	}
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	int a = jTable1.getSelectedRow();
        int aa=(int)jTable1.getValueAt(a,0);
        String ab=jTable1.getValueAt(a,3).toString();
        String message = "Job already verified cannot be removed";
        
        if(ab.equalsIgnoreCase("Verified")){
        	
        	JOptionPane.showMessageDialog(new JFrame(), message,
					"Alerte", JOptionPane.INFORMATION_MESSAGE);
        	
        }
        else {
        	System.out.println(ab);
        	System.out.println(aa);
            proxy.removeJob(aa);
            a();
        	
					}
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Home frame = new Home();
		frame.setVisible(true); 
		dispose();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
